repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Format
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: pretty-format-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: CHANGELOG.md
      - id: check-executables-have-shebangs

      # Git style
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: forbid-new-submodules
      - id: no-commit-to-branch

      # Cross platform
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf]

      # Security
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: detect-private-key

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shfmt
        args: ['-l', '-i', '2', '-ci', '-sr', '-w']
      - id: shellcheck

  - repo: local
    hooks:
      - id: terraform_fmt
        name: terraform_fmt
        description: Rewrites all Terraform configuration files to a canonical format.
        language: docker_image
        entry: --entrypoint xargs ghcr.io/antonbabenko/pre-commit-terraform:latest tools/terraform_fmt.sh
        files: (\.tf|\.tfvars)$
        exclude: \.terraform\/.*$
      - id: terraform_docs
        name: terraform_docs
        description: Inserts input and output documentation into README.md (using terraform-docs).
        require_serial: true
        language: docker_image
        args:
          - --hook-config=--path-to-file=README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
          - --hook-config=--add-to-existing-file=true     # Boolean. true or false
          #- --hook-config=--create-file-if-not-exist=true
        entry: --entrypoint xargs ghcr.io/antonbabenko/pre-commit-terraform:latest tools/terraform_docs.sh
        files: (README\.md|\.tf|\.terraform\.lock\.hcl)$
        exclude: \.terraform\/.*$
      - id: terraform_tflint
        name: terraform_tflint
        description: Validates all Terraform configuration files with TFLint.
        language: docker_image
        entry: --entrypoint xargs ghcr.io/antonbabenko/pre-commit-terraform:latest tools/terraform_tflint.sh
        files: (\.tf|\.tfvars)$
        exclude: \.terraform\/.*$
      - id: terraform_validate
        description: Validates all Terraform configuration files.
        name: terraform_validate
        language: docker_image
        entry: --entrypoint xargs ghcr.io/antonbabenko/pre-commit-terraform:latest tools/terraform_validate.sh
        files: (\.tf|\.tfvars)$
        exclude: \.terraform\/.*$
      - id: terraform_tfsec
        language: docker_image
        name: Terraform validate with tfsec
        description: Static analysis of Terraform templates to spot potential security issues.
        entry: --entrypoint xargs ghcr.io/antonbabenko/pre-commit-terraform:latest tools/terraform_tfsec.sh
        require_serial: true
      - id: terraform_checkov
        name: terraform_checkov
        description: Runs checkov on Terraform templates.
        language: docker_image
        pass_filenames: false
        always_run: false
        files: \.tf$
        exclude: \.terraform\/.*$
        require_serial: true
        entry: --entrypoint xargs ghcr.io/antonbabenko/pre-commit-terraform:latest tools/terraform_checkov.sh
      - id: terraform_providers_lock
        name: terraform_providers_lock
        description: Updates provider signatures in dependency lock files.
        language: docker_image
        require_serial: true
        files: (\.terraform\.lock\.hcl)$
        exclude: \.terraform\/.*$
        entry: --entrypoint xargs ghcr.io/antonbabenko/pre-commit-terraform:latest tools/terraform_providers_lock.sh
      - id: tfupdate
        name: tfupdate
        description: Runs tfupdate on Terraform templates.
        language: docker_image
        entry: --entrypoint xargs ghcr.io/antonbabenko/pre-commit-terraform:latest tools/tfupdate.sh
        args:
          - --args=terraform
        files: \.tf$
        require_serial: true
