on:
  schedule:
    - cron: "0 0 1 * *"
  # manual trigger
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v1.1.1
        with:
          github_token: ${{ secrets.TOKEN_VCS }}
          source_repo_path: weni-ai/infra-weni-template
          #upstream_branch: <target_branch> # defaults to main
          #pr_labels: <label1>,<label2>[,...] # optional, no default
