name: 'Test basic rules for terraform'

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-shfmt@v1
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
        env:
          SKIP: no-commit-to-branch
